bootstrap_form/urls.py
from django.urls import path

# bootstrap_form/form
# namespace = "boot_form"
from . import views
urlpatterns = [
	path('form/', views.form, name = "form"),
	path('form_edit/<int:pk>', views.form_edit, name = "form_edit"),
	path('form_delete/<int:pk>', views.form_delete, name = "form_delete")
]

core/urls.py
from django.urls import path
from .views import  (   home, render_html, contact_us, 
                        PorductListView,  ProductDetailView, 
                        FeaturedProduct, ProductSlugView) 
urlpatterns = [
    path('', home, name="home"), 
    path('render_html/', render_html),
    path('contact_us/', contact_us),
    path('list/', PorductListView.as_view()),
    path('detail/<int:pk>/', ProductDetailView.as_view()),
    path('featured/', FeaturedProduct.as_view()),
    path('slug/<slug:slug>/', ProductSlugView.as_view() , name="slug_name"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include



urlpatterns = [
#   path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('article/', include('albums.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('products/', include(("core.urls", "products"), namespace = 'products' )),
    path('country/', include('country.urls')),
    path('city/', include('grouby_example.urls')),
    path('bootstrap_form/', include(('bootstrap_form.urls', 'bootstrap_form'), namespace="boot_form")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
                                    settings.STATIC_URL, 
                                    document_root = settings.STATIC_ROOT
                                )
    urlpatterns = urlpatterns + static(
                                    settings.MEDIA_URL, 
                                    document_root=settings.MEDIA_ROOT
                                )

bootstrap_form/models.py
from django.db import models
class ContactUs(models.Model):
	name = models.CharField(max_length = 30)
	email = models.EmailField(max_length = 100)
	address = models.CharField(max_length = 100)

	def __str__(self):
		return self.name

bootstrap_form/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import ContactUs 

def form(request):
	rec = None
	if request.GET.get('method') == 'edit':
		rec = ContactUs.objects.filter(id = request.GET.get('id')).get()
	elif request.GET.get('method') == 'delete':
		rec = ContactUs.objects.filter(id = request.GET.get('id')).get()
		rec.delete()
		return HttpResponseRedirect('/bootstrap_form/form') 
		
	if request.method == 'POST':
		if request.GET.get('method') == 'edit':
			rec.name = request.POST.get('name')
			rec.email = request.POST.get('email')
			rec.address = request.POST.get('address')
			rec.save()

			return HttpResponseRedirect('/bootstrap_form/form') 
		else:
			contact = ContactUs(
				name = request.POST.get('name'),
				email = request.POST.get('email'),
				address = request.POST.get('address')
			) 
			contact.save()
	data = ContactUs.objects.all()	
	return render(request, 'bootstrap_form/index.html', {'data':data , 'rec': rec })

def form_delete(request):
	pass

def form_edit(request):
	pass

templates/bootstrap_form/index.html
{% extends 'base_template.html' %}
{% block content %}
<form method="post">

{% if rec == None %}
	name
	<input type ="text" name = "name">
	<br/>
	email
	<input type="text" name="email">
	<br/>
	address
	<input type ="text" name="address">
	<br>
{% else %}
	name
	<input value='{{rec.name }}' type ="text" name = "name">
	<br/>
	email
	<input value='{{rec.email }}' type="text" name="email">
	<br/>
	address
	<input type ="text" value='{{ rec.address }}' name="address">
	<br>
{% endif %}
<input type="submit">
{% csrf_token %}
</form>
<table border="2px soild">
<tr>	<th>Email</th> <th> Name </th> <th> Phone</th> <th> Action</th> </tr>
{% for row in data %}
<tr>
	<td> {{ row.email }} </td>
	<td> {{ row.name }} </td>
	<td> {{ row.address }} </td>
	<td> 
		<a href="{% url 'boot_form:form'  %}?id={{row.id}}&method=edit">Edit</a>   
		<a href="{% url 'boot_form:form'  %}?id={{row.id}}&method=delete">Delete</a> 
	</td>
<tr>
{% endfor %}
</table>

{% endblock %}

<!--
email: {{ email|default:"None" }} , name: {{ name|default:"None" }} , phone: {{ phone|default:"None" }}
-->