core/urls.py
from django.urls import path
from .views import  (   home, render_html, contact_us, 
                        PorductListView,  ProductDetailView, 
                        FeaturedProduct, ProductSlugView) 
urlpatterns = [
    path('', home, name="home"), 
    path('render_html/', render_html),
    path('contact_us/', contact_us),
    path('list/', PorductListView.as_view()),
    path('detail/<int:pk>/', ProductDetailView.as_view()),
    path('featured/', FeaturedProduct.as_view()),
    path('slug/<slug:slug>/', ProductSlugView.as_view() , name="slug_name"),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include



urlpatterns = [
#   path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path('article/', include('albums.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('products/', include(("core.urls", "products"), namespace = 'products' )),
    path('country/', include('country.urls')),
    path('city/', include('grouby_example.urls')),
    path('bootstrap_form/', include(('bootstrap_form.urls', 'bootstrap_form'), namespace="boot_form")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
                                    settings.STATIC_URL, 
                                    document_root = settings.STATIC_ROOT
                                )
    urlpatterns = urlpatterns + static(
                                    settings.MEDIA_URL, 
                                    document_root=settings.MEDIA_ROOT
                                )

templates/products/detail.html
{{object}}
<br>
<br>
{{ object.title }}
<br>
<br>{{ object.description}}
<br><br>
{% if object.image %}
<img src="{{ object.image.url}}" height="500px" width="500px">
{% endif %}

templates/products/list.html
{% extends 'base_template.html' %}

{% block content %}
{{ object_list }}
{% for obj in object_list %}
<br/>
<br/>
<a href="{{ obj.slug_url }}"> {{ obj.title }} </a>
<a href="{% url 'products:slug_name' slug=obj.slug %}"> {{ obj.title }} </a>
<a href="{{ obj.slug_reverse_url }}"> {{ obj.title }} </a>
<br/>
<br/>
{% endfor %}

{{ text }}

{% endblock %}